# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "VM1-GRUPO-ASANCHEZ" do |vmHost1|
    vmHost1.vm.box = "ubuntu/jammy64"
    vmHost1.vm.hostname = "testing"
    vmHost1.vm.network "private_network", :name => '', ip: "192.168.56.10"
    
# Comparto la carpeta del host donde estoy parado contra la vm
    vmHost1.vm.synced_folder 'compartido_Host1/', '/home/vagrant/compartido', 
    owner: 'vagrant', group: 'vagrant' 

# Agrega la key Privada de ssh en .vagrant/machines/default/virtualbox/private_key
      vmHost1.ssh.insert_key = true

# Agrego un nuevo disco 
      vmHost1.vm.disk :disk, size: "1GB", name: "#{vmHost1.vm.hostname}_extra_storage"
      vmHost1.vm.disk :disk, size: "2GB", name: "#{vmHost1.vm.hostname}_extra_storage2"
      vmHost1.vm.disk :disk, size: "3GB", name: "#{vmHost1.vm.hostname}_extra_storage3"
      vmHost1.vm.disk :disk, size: "5GB", name: "#{vmHost1.vm.hostname}_extra_storage4"

      vmHost1.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "testing"
        vb.cpus = 1
        vb.linked_clone = true
        
# Seteo controladora Grafica
        vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']      
      end    

#Agrego los host
    vmHost1.vm.provision "shell", inline: <<-SHELL
      grep -q "testing" /etc/hosts || echo "192.168.56.10 testing" >> /etc/hosts
      grep -q "produccion" /etc/hosts || echo "192.168.56.11 produccion" >> /etc/hosts
    SHELL

#Configuro sudo sin password
    vmHost1.vm.provision "shell", inline: <<-SHELL
    echo "vagrant ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/vagrant
    chmod 0440 /etc/sudoers.d/vagrant
  SHELL


# Puedo Ejecutar un script que esta en un archivo
      vmHost1.vm.provision "shell",privileged: false, path: "script_Enable_ssh_password.sh"
      vmHost1.vm.provision "shell", privileged: false, path: "script_Fix_history.sh"
      vmHost1.vm.provision "shell",privileged: true, path: "instala_paquetes.sh"
  vmHost1.vm.provision "shell", privileged: false,  path: "script_ssh_keygen.sh" 
    end


    
      config.vm.define "VM2-GRUPO-ASANCHEZ"  do |vmHost2|
      vmHost2.vm.box = "bento/fedora-39"
      vmHost2.vm.hostname = "produccion"
      vmHost2.vm.network "private_network", ip: "192.168.56.12", auto_config: true
      
# Comparto la carpeta del host donde estoy parado contra la vm
      vmHost2.vm.synced_folder 'compartido_Host2/', '/home/vagrant/compartido'
  
# Agrega la key Privada de ssh en .vagrant/machines/default/virtualbox/private_key
    vmHost2.ssh.insert_key = true
    
# Agrego un nuevo disco
      vmHost2.vm.disk :disk, size: "1GB", name: "#{vmHost2.vm.hostname}_extra_storage"
      vmHost2.vm.disk :disk, size: "2GB", name: "#{vmHost2.vm.hostname}_extra_storage2"
      vmHost2.vm.disk :disk, size: "3GB", name: "#{vmHost2.vm.hostname}_extra_storage3"
      vmHost2.vm.disk :disk, size: "5GB", name: "#{vmHost2.vm.hostname}_extra_storage4"


      vmHost2.vm.provider "virtualbox" do |vb2|
      vb2.memory = "1024"
      vb2.name = "produccion"
      vb2.cpus = 1
      vb2.linked_clone = true
      
# Seteo controladora Grafica
      vb2.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end

#Agrego los host
    vmHost2.vm.provision "shell", inline: <<-SHELL
      grep -q "testing" /etc/hosts || echo "192.168.56.10 testing" >> /etc/hosts
      grep -q "produccion" /etc/hosts || echo "192.168.56.11 produccion" >> /etc/hosts
    SHELL
     
#Configuracion manual de ip
     vmHost2.vm.provision "shell", inline: <<-SHELL
  CONN=$(nmcli -t -f NAME,DEVICE con show --active | awk -F: '$2=="eth1"{print $1}')
      nmcli con mod "$CONN" ipv4.addresses 192.168.56.11/24
      nmcli con mod "$CONN" ipv4.method manual
      nmcli con up "$CONN"
      SHELL

#Configuro sudo sin password (inline: <<SHELL comando directos SHELL)

 vmHost2.vm.provision "shell", inline: <<-SHELL
    echo "vagrant ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/vagrant
    chmod 0440 /etc/sudoers.d/vagrant
  SHELL
    
    
# Ejecuto los scripts
    vmHost2.vm.provision "shell",privileged: false, path: "script_Enable_ssh_password.sh"
    vmHost2.vm.provision "shell", privileged: false, path: "script_Fix_history.sh"
    vmHost2.vm.provision "shell",privileged: true, path: "instala_paquetes_fedora.sh"
    vmHost2.vm.provision "shell",privileged: false, path: "script_ssh_keygen.sh"


  end
end
