---
- hosts: 
#  - all
  - testing
  - produccion

  # Variables Globales
  vars_files:
    - vars/main.yml

  tasks:
    - include_role:
        name: TP_INI_ASANCHEZ

    - include_role:
        name: Alta_Usuarios_ASANCHEZ

    - include_role:
        name: Sudoers_ASANCHEZ
    
    - include_role:
        name: Instala_Tool_ASANCHEZ


